### ISSUE TITLE
MCX adapter for Sampler, BNC-DIO, IDC-BNC

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/MCX_BNC_adapter#1]
Technosystem volunteered to design a simple adapter that can be mounted instead of BNC connectors and utilize existing boards with 4HP panels. In this way, all modules already available with BNC connectors can be easily modified with MCX or other connectivity option.
Moreover, existing modules can be easily transformed by the users to 4HP by ordering kits containing adapter and 4 HP panel. In this way, it will be much easier to manage the stock of boards and offer various configuration options.
What do you think? @jordens @hartytp

**Comment by gkasprow** [comment]
I don't have a photo, but I have a PCB with it :)

**Comment by gkasprow** [comment]
![2021-05-17 21 32 53](https://user-images.githubusercontent.com/4325054/118546101-c6c88580-b757-11eb-96b3-d54c49b28f5a.jpg)
![2021-05-17 21 33 03](https://user-images.githubusercontent.com/4325054/118546107-c92adf80-b757-11eb-8150-b08fa10bac3e.jpg)

**Comment by gkasprow** [comment]
the panel was 3D-printed

**Comment by jordens** [comment]
Thanks!
